---
openapi: 3.0.3
info:
  title: Workflow Deployment Management API
  description: Workflow Deployment Management API server.
  contact:
    name: FIS3 - Workflow Team
    url: http://LoremIpsum.hlag.com
    email: LoremIpsum@hlag.com
  version: "1.0"
tags:
- name: Workflow Deployment Resource
  description: Camunda's workflow deployment via Camunda Zeebe Engine and Postgresql
- name: Workflow Validation Resource
  description: Camunda's workflow validation using common HLAG rules
- name: Workflow Version Resource
  description: Camunda's workflow version management resources via Camunda Zeebe Engine
    and Postgresql
paths:
  /workflow-deployment-management/deploy:
    get:
      tags:
      - Workflow Deployment Resource
      summary: List Workflow deployment results
      description: List Workflow deployment results that are not deleted
      parameters:
      - name: page
        in: query
        schema:
          format: int32
          type: integer
      - name: pageSize
        in: query
        schema:
          format: int32
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagingResultWrapperWorkflowDeployClusterDto'
    post:
      tags:
      - Workflow Deployment Resource
      summary: Deploy Workflow resource files
      description: "Check the changes and deploy updated Camunda files into Camunda\
        \ platform, also validate the files using the common rules"
      requestBody:
        description: Bpmn / Dmn files for deployment
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileUploads:
                  type: array
                  items:
                    $ref: '#/components/schemas/FileUploadSchema'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowDeployClusterDto'
  /workflow-deployment-management/deploy/{id}:
    get:
      tags:
      - Workflow Deployment Resource
      summary: Get Workflow deployment information by its Id
      description: "Get the Workflow deployment information by its Id, including the\
        \ detail of the files in the batch and the corresponding validation results."
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowDeployClusterDto'
  /workflow-deployment-management/validate:
    get:
      tags:
      - Workflow Validation Resource
      summary: List all validation results
      description: List all validation results that are not deleted
      parameters:
      - name: page
        in: query
        schema:
          format: int32
          type: integer
      - name: pageSize
        in: query
        schema:
          format: int32
          type: integer
      - name: valid
        in: query
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagingResultWrapperWorkflowValidationClusterDto'
    post:
      tags:
      - Workflow Validation Resource
      summary: Validate input files
      description: "Validate input files using common HLAG rules. For more information,\
        \ please visit the [Confluence page](https://confluence.hlag.com/display/BASS/Naming+of+Camunda+Artefacts)."
      requestBody:
        description: Bpmn / Dmn files for validation
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileUploads:
                  type: array
                  items:
                    $ref: '#/components/schemas/FileUploadSchema'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowValidationClusterDto'
  /workflow-deployment-management/validate/{id}:
    get:
      tags:
      - Workflow Validation Resource
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowValidationClusterDto'
  /workflow-deployment-management/version:
    get:
      tags:
      - Workflow Version Resource
      summary: List active workflows
      description: List Workflow's latest active version which is normally used for
        operations
      parameters:
      - name: page
        in: query
        schema:
          format: int32
          type: integer
      - name: pageSize
        in: query
        schema:
          format: int32
          type: integer
      - name: processId
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagingResultWrapperWorkflowVersionDto'
  /workflow-deployment-management/version/{processId}:
    get:
      tags:
      - Workflow Version Resource
      summary: List all Workflow versions by processId
      description: "List all Workflow versions by processId, which includes old versions\
        \ that's no longer active"
      parameters:
      - name: processId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkflowVersionDto'
components:
  schemas:
    FileUpload:
      type: object
    FileUploadSchema:
      $ref: '#/components/schemas/FileUploadSchema'
    IgnoredFile:
      type: object
      properties:
        fileName:
          type: string
        reason:
          type: string
    InvalidId:
      type: object
      properties:
        id:
          type: string
        reason:
          type: string
    LocalDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50
    PagingInfo:
      type: object
      properties:
        index:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        total:
          format: int64
          type: integer
    PagingResultWrapperWorkflowDeployClusterDto:
      type: object
      properties:
        pagingInfo:
          $ref: '#/components/schemas/PagingInfo'
        item:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowDeployClusterDto'
    PagingResultWrapperWorkflowValidationClusterDto:
      type: object
      properties:
        pagingInfo:
          $ref: '#/components/schemas/PagingInfo'
        item:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowValidationClusterDto'
    PagingResultWrapperWorkflowVersionDto:
      type: object
      properties:
        pagingInfo:
          $ref: '#/components/schemas/PagingInfo'
        item:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowVersionDto'
    WorkflowDeployClusterDto:
      type: object
      properties:
        id:
          type: string
        deployedFiles:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowVersionDto'
        ignoredFiles:
          type: array
          items:
            $ref: '#/components/schemas/IgnoredFile'
        invalidFiles:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowValidationDto'
        created:
          $ref: '#/components/schemas/LocalDateTime'
        warning:
          type: boolean
        validationClusterId:
          type: string
    WorkflowValidationClusterDto:
      type: object
      properties:
        id:
          type: string
        workflowValidations:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowValidationDto'
        valid:
          type: boolean
        created:
          $ref: '#/components/schemas/LocalDateTime'
        deploymentId:
          type: string
    WorkflowValidationDto:
      type: object
      properties:
        fileName:
          type: string
        valid:
          type: boolean
        invalidIds:
          type: array
          items:
            $ref: '#/components/schemas/InvalidId'
    WorkflowVersionDto:
      type: object
      properties:
        processId:
          type: string
        version:
          format: int32
          type: integer
        fileName:
          type: string
        camundaKey:
          format: int64
          type: integer
        deprecated:
          type: boolean
        created:
          $ref: '#/components/schemas/LocalDateTime'
        valid:
          type: boolean
        clusterId:
          type: string
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
